In [1]:
from __future__ import print_function
import numpy as np
import tensorflow as tf
from six.moves import cPickle as pickle
from six.moves import range

In [ ]:
# # Now as always we get the data we stored in the disk.
# cleaned_dataset_path = '/Users/sam/All-Program/App-DataSet/Deep-Neural-Nets/MNIST_ImageClassification/DataPreparation/dataset_cleaned.p'

# with open(cleaned_dataset_path, 'rb') as f:
#     fnl_dataset = pickle.load(f)
#     training_dataset = (fnl_dataset['training_dataset'])
#     training_labels = (fnl_dataset['training_labels'])
#     test_dataset = (fnl_dataset['test_dataset'])
#     test_labels = (fnl_dataset['test_labels'])
#     crossvalid_dataset = (fnl_dataset['crossvalid_dataset'])
#     crossvalid_labels = (fnl_dataset['crossvalid_labels'])
    
# print('Training:', training_dataset.shape, training_labels.shape)
# print('Cross Validation:', crossvalid_dataset.shape, crossvalid_labels.shape)
# print('Testing:', test_dataset.shape, test_labels.shape)

In [ ]:
# # Mini-Batch Creation
# no_of_batches = 200
# batch_indices = []
# def batch_indice_creator(training_labels, no_of_batches):
#     """Create batch with random samples and return appropriate format"""
#     label_rand_arr = []
#     no_of_labels = len(np.unique(training_labels))
    
#     if len(training_labels)/no_of_batches < no_of_labels:
#         raise Exception ("Every batch should contain atleast 1 example from all the differnt class labels")
#     else:
#         for unq_labels in np.unique(training_labels):
#             arr = np.array(np.where(training_labels==unq_labels)[0])
#             print ('Total number of label %d is :'%unq_labels, len(arr))
#             np.random.shuffle(arr)
#     #         print ('the random array is: ', np.reshape(arr, (len(arr),1)))
#             if np.any(label_rand_arr):
#                 label_rand_arr = np.hstack((label_rand_arr, np.reshape(arr, (len(arr),1))))
#             else:
#                 label_rand_arr = np.reshape(arr, (len(arr),1))
        
#         no_of_batches_new = no_of_batches
#         if label_rand_arr.shape[0]%no_of_batches!=0:
#             no_of_batches_new = no_of_batches + label_rand_arr.shape[0]%no_of_batches
#             print ('Provided no_of_batches doesnt distribute the labels equally, ne no_of_batches is: ', no_of_batches_new) 
#         batch_indices = np.array_split(label_rand_arr.flatten(), no_of_batches_new)
#         batch_size = len(batch_indices[0])
#     return batch_indices, batch_size


# training_batch_dir = '/Users/sam/All-Program/App-DataSet/Deep-Neural-Nets/MNIST_ImageClassification/DataPreparation/'        
# batch_training_dict = {}
# def batch_store(training_dataset, training_labels, batch_indices):
#     for no, indices in enumerate(batch_indices):
#         #print (training_labels[indices])
#         try:
#             f = open(training_batch_dir+'batch'+str(no)+'.pickle', 'wb')
#             batch = {
#                 'batch_train_dataset': training_dataset[indices],
#                 'batch_train_labels': training_labels[indices],
#             }
#             pickle.dump(batch, f, pickle.HIGHEST_PROTOCOL)
#             f.close()
#         except Exception as e:
#             print('Unable to save data to', complete_dataset_path, ':', e)
#             raise
            
# batch_indices, batch_size = batch_indice_creator(training_labels, no_of_batches)  #print ([arr.shape for arr in batch_indices])
# #batch_store(training_dataset, training_labels, batch_indices)

# print ('the batch size is:',batch_size )

In [ ]:
# image_size = 28
# no_of_labels = 10
# no_inp_unit = image_size * image_size

# # tensor flow takes the labels input as binary code, where Alphabet A whose binary value is 0 will turn to a array
# # with elements [1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0] and B becomes [0, 1.0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
# def reshape_data(dataset, labels, sample_size=None):
#     if sample_size:
#         dataset = dataset[:sample_size].reshape(sample_size, no_inp_unit) # To reshape the  
#         # Map 0 to [1.0, 0.0, 0.0 ...], 1 to [0.0, 1.0, 0.0 ...]
#         labels = (np.arange(no_of_labels) == labels[:,None]).astype(np.float32)
#     else:
#         dataset = dataset.reshape(len(dataset), no_inp_unit) # To reshape the  
#         # Map 0 to [1.0, 0.0, 0.0 ...], 1 to [0.0, 1.0, 0.0 ...]
#         labels = (np.arange(no_of_labels) == labels[:,None]).astype(np.float32)
#     return dataset, labels

# # We just reshape the image so that 1 image defines a row

# crossvalid_dataset_, crossvalid_labels_ = reshape_data(crossvalid_dataset, crossvalid_labels)
# test_dataset_, test_labels_ = reshape_data(test_dataset, test_labels)
# print('Cross Validation set', crossvalid_dataset_.shape, crossvalid_labels_.shape)
# print('Test set', test_dataset_.shape, test_labels_.shape)

In [ ]:
# import tensorflow as tf
# from tensorflow.examples.tutorials.mnist import input_data
# mnist = input_data.read_data_sets("/tmp/data/", one_hot = True)

# n_nodes_hl1 = 500
# n_nodes_hl2 = 500
# n_nodes_hl3 = 500

# n_classes = 10
# batch_size = 100

# x = tf.placeholder('float', [None, 784])
# y = tf.placeholder('float')

# def neural_network_model(data):
#     hidden_1_layer = {'weights':tf.Variable(tf.random_normal([784, n_nodes_hl1])),
#                       'biases':tf.Variable(tf.random_normal([n_nodes_hl1]))}

#     hidden_2_layer = {'weights':tf.Variable(tf.random_normal([n_nodes_hl1, n_nodes_hl2])),
#                       'biases':tf.Variable(tf.random_normal([n_nodes_hl2]))}

#     hidden_3_layer = {'weights':tf.Variable(tf.random_normal([n_nodes_hl2, n_nodes_hl3])),
#                       'biases':tf.Variable(tf.random_normal([n_nodes_hl3]))}

#     output_layer = {'weights':tf.Variable(tf.random_normal([n_nodes_hl3, n_classes])),
#                     'biases':tf.Variable(tf.random_normal([n_classes])),}


#     l1 = tf.add(tf.matmul(data,hidden_1_layer['weights']), hidden_1_layer['biases'])
#     l1 = tf.nn.relu(l1)

#     l2 = tf.add(tf.matmul(l1,hidden_2_layer['weights']), hidden_2_layer['biases'])
#     l2 = tf.nn.relu(l2)

#     l3 = tf.add(tf.matmul(l2,hidden_3_layer['weights']), hidden_3_layer['biases'])
#     l3 = tf.nn.relu(l3)

#     output = tf.matmul(l3,output_layer['weights']) + output_layer['biases']

#     return output

# def train_neural_network(x):
#     prediction = neural_network_model(x)
#     cost = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits(prediction,y) )
#     optimizer = tf.train.AdamOptimizer().minimize(cost)
    
#     hm_epochs = 10
#     with tf.Session() as sess:
#         sess.run(tf.initialize_all_variables())

#         for epoch in range(hm_epochs):
#             epoch_loss = 0
#             for _ in range(int(mnist.train.num_examples/batch_size)):
#                 epoch_x, epoch_y = mnist.train.next_batch(batch_size)
#                 _, c = sess.run([optimizer, cost], feed_dict={x: epoch_x, y: epoch_y})
#                 epoch_loss += c

#             print('Epoch', epoch, 'completed out of',hm_epochs,'loss:',epoch_loss)

#         correct = tf.equal(tf.argmax(prediction, 1), tf.argmax(y, 1))

#         accuracy = tf.reduce_mean(tf.cast(correct, 'float'))
#         print('Accuracy:',accuracy.eval({x:mnist.test.images, y:mnist.test.labels}))

# train_neural_network(x)

In [1]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
from tensorflow.python.ops import rnn, rnn_cell
mnist = input_data.read_data_sets("/tmp/data/", one_hot = True)

hm_epochs = 3
n_classes = 10
batch_size = 128
chunk_size = 28
n_chunks = 28
rnn_size = 128


x = tf.placeholder('float', [None, n_chunks,chunk_size])
y = tf.placeholder('float')


Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting /tmp/data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz


In [7]:
print (x.get_shape())
#print (y.shape)

(?, 28, 28)


In [3]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
from tensorflow.python.ops import rnn, rnn_cell
mnist = input_data.read_data_sets("/tmp/data/", one_hot = True)

hm_epochs = 3
n_classes = 10
batch_size = 128
chunk_size = 28  # 28 pickles would comprise of 1 chunck
n_chunks = 28    # for one image of 28*28, we decide 28 sequences
no_of_hid_units = 128


x = tf.placeholder('float', [None, n_chunks,chunk_size])
y = tf.placeholder('float')

def recurrent_neural_network(x):
    layer = {'weights':tf.Variable(tf.random_normal([rnn_size,n_classes])),
             'biases':tf.Variable(tf.random_normal([n_classes]))}

    x = tf.transpose(x, [1,0,2])
    x = tf.reshape(x, [-1, chunk_size])
    x = tf.split(0, n_chunks, x)

    lstm_cell = rnn_cell.BasicLSTMCell(no_of_hid_units,state_is_tuple=True)
    outputs, states = rnn.rnn(lstm_cell, x, dtype=tf.float32)
#     print ('The shape of the output is given as: ', outputs.get_shape())
#     print ('The second shape of the output is given as ', outputs[-1].get_shape())
    output = tf.matmul(outputs[-1],layer['weights']) + layer['biases']

    return output

Extracting /tmp/data/train-images-idx3-ubyte.gz
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz


In [12]:
def train_neural_network(x):
#     prediction = recurrent_neural_network(x)
#     cost = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits(prediction,y) )
#     optimizer = tf.train.AdamOptimizer().minimize(cost)
    
    
    with tf.Session() as sess:
        sess.run(tf.initialize_all_variables())

        for epoch in range(hm_epochs):
            epoch_loss = 0
            for i in range(int(mnist.train.num_examples/batch_size)):
                print (i)
                epoch_x, epoch_y = mnist.train.next_batch(batch_size)
                print (epoch_x.shape)
                print (epoch_x
                
                break
            break
#                 epoch_x = epoch_x.reshape((batch_size,n_chunks,chunk_size))

#                 _, c = sess.run([optimizer, cost], feed_dict={x: epoch_x, y: epoch_y})
#                 epoch_loss += c

#             print('Epoch', epoch, 'completed out of',hm_epochs,'loss:',epoch_loss)

#         correct = tf.equal(tf.argmax(prediction, 1), tf.argmax(y, 1))

#         accuracy = tf.reduce_mean(tf.cast(correct, 'float'))
#         print('Accuracy:',accuracy.eval({x:mnist.test.images.reshape((-1, n_chunks, chunk_size)), y:mnist.test.labels}))

train_neural_network(x)



0
(128, 784)
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]


In [20]:
import numpy as np
# a = np.array([1,2,3,4,5,6])
# np.transpose(a, (1,0,2))

a = np.array([[[ 1.,  2.,  3.], [ 4.,  5.,  6.]]])
#a = np.ones((1,2,3))
print (a)
np.transpose(a, (1,0,2))
np.reshape(a, [-1, 1])


[[[ 1.  2.  3.]
  [ 4.  5.  6.]]]


array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.]])